# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信UnionID')),
                ('wechat_info', models.JSONField(default=dict, verbose_name='微信用户信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级用户')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dietary_preferences', models.JSONField(default=dict, verbose_name='饮食偏好')),
                ('allergies', models.JSONField(default=list, verbose_name='过敏食物')),
                ('disliked_foods', models.JSONField(default=list, verbose_name='不喜欢的食物')),
                ('total_dishes_created', models.PositiveIntegerField(default=0, verbose_name='创建菜品数')),
                ('total_dishes_cooked', models.PositiveIntegerField(default=0, verbose_name='烹饪菜品数')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('cooking_experience', models.CharField(choices=[('beginner', '新手'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='beginner', max_length=20, verbose_name='烹饪经验')),
                ('preferred_cuisines', models.JSONField(default=list, verbose_name='偏好菜系')),
                ('preferred_cooking_time', models.CharField(choices=[('quick', '快速（15分钟内）'), ('medium', '中等（15-30分钟）'), ('long', '较慢（30-60分钟）'), ('very_long', '慢炖（60分钟以上）')], default='medium', max_length=20, verbose_name='偏好烹饪时间')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='启用通知')),
                ('enable_meal_reminders', models.BooleanField(default=True, verbose_name='用餐提醒')),
                ('enable_new_dish_notifications', models.BooleanField(default=True, verbose_name='新菜品通知')),
                ('show_profile_public', models.BooleanField(default=True, verbose_name='公开个人资料')),
                ('show_cooked_dishes', models.BooleanField(default=True, verbose_name='显示烹饪记录')),
                ('show_created_dishes', models.BooleanField(default=True, verbose_name='显示创建菜品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('phone', '手机号登录'), ('wechat', '微信登录'), ('token', 'Token登录')], max_length=20, verbose_name='登录方式')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='设备ID')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='应用版本')),
                ('os_version', models.CharField(blank=True, max_length=20, verbose_name='系统版本')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('network_type', models.CharField(blank=True, max_length=20, verbose_name='网络类型')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='登录地点')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失败原因')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='登出时间')),
                ('session_duration', models.DurationField(blank=True, null=True, verbose_name='会话时长')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create_dish', '创建菜品'), ('update_dish', '更新菜品'), ('delete_dish', '删除菜品'), ('cook_dish', '烹饪菜品'), ('view_dish', '查看菜品'), ('search', '搜索'), ('share', '分享'), ('rate', '评分'), ('comment', '评论')], max_length=20, verbose_name='活动类型')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='目标ID')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='目标类型')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_290628_idx'), models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx')],
            },
        ),
    ]
