# Generated by Django 4.2.7 on 2026-06-22 07:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('read', '读取'), ('download', '下载'), ('preview', '预览'), ('share', '分享'), ('delete', '删除'), ('update', '更新')], max_length=20, verbose_name='访问类型')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('referrer', models.URLField(blank=True, verbose_name='来源URL')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('status_code', models.PositiveSmallIntegerField(default=200, verbose_name='状态码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('bytes_transferred', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='传输字节数')),
                ('response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='响应时间(秒)')),
                ('cache_status', models.CharField(blank=True, max_length=20, verbose_name='缓存状态')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '文件访问日志',
                'verbose_name_plural': '文件访问日志',
                'db_table': 'file_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='分享令牌')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='访问密码')),
                ('description', models.TextField(blank=True, verbose_name='分享描述')),
                ('max_views', models.PositiveIntegerField(default=0, verbose_name='最大查看次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('require_password', models.BooleanField(default=False, verbose_name='需要密码')),
                ('allow_download', models.BooleanField(default=True, verbose_name='允许下载')),
                ('allow_preview', models.BooleanField(default=True, verbose_name='允许预览')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件分享链接',
                'verbose_name_plural': '文件分享链接',
                'db_table': 'file_share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('resize', '调整大小'), ('crop', '裁剪'), ('compress', '压缩'), ('watermark', '添加水印'), ('format_convert', '格式转换'), ('optimize', '优化'), ('multiple', '多操作')], max_length=20, verbose_name='任务类型')),
                ('parameters', models.JSONField(default=dict, verbose_name='处理参数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('processing_data', models.JSONField(default=dict, verbose_name='处理数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='处理时间(秒)')),
                ('memory_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='内存使用(字节)')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='质量评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '图片处理任务',
                'verbose_name_plural': '图片处理任务',
                'db_table': 'image_processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_storage_bytes', models.PositiveBigIntegerField(default=10737418240, verbose_name='最大存储空间(字节)')),
                ('max_file_size', models.PositiveBigIntegerField(default=104857600, verbose_name='最大文件大小(字节)')),
                ('max_files_per_day', models.PositiveIntegerField(default=100, verbose_name='每日最大文件数')),
                ('used_storage_bytes', models.PositiveBigIntegerField(default=0, verbose_name='已用存储空间(字节)')),
                ('files_uploaded_today', models.PositiveIntegerField(default=0, verbose_name='今日已上传文件数')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='总文件数')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='最后重置日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '存储配额',
                'verbose_name_plural': '存储配额',
                'db_table': 'storage_quotas',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='存储文件名')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('document', '文档'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('file_extension', models.CharField(max_length=20, verbose_name='文件扩展名')),
                ('storage_path', models.CharField(max_length=500, verbose_name='存储路径')),
                ('storage_provider', models.CharField(default='local', max_length=50, verbose_name='存储提供商')),
                ('storage_url', models.URLField(blank=True, verbose_name='存储URL')),
                ('cdn_url', models.URLField(blank=True, verbose_name='CDN URL')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('deleted', '已删除')], default='pending', max_length=20, verbose_name='状态')),
                ('processing_data', models.JSONField(default=dict, verbose_name='处理数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='访问密钥')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
