# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='storagequota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='result_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_from', to='upload.uploadedfile', verbose_name='结果文件'),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='upload.uploadedfile', verbose_name='上传文件'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='upload.uploadedfile', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='upload.uploadedfile', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'file_type'], name='uploaded_fi_user_id_b71b74_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['status'], name='uploaded_fi_status_e2833e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['created_at'], name='uploaded_fi_created_f8998f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessingjob',
            index=models.Index(fields=['uploaded_file', 'job_type'], name='image_proce_uploade_26b441_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessingjob',
            index=models.Index(fields=['status'], name='image_proce_status_1aba23_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessingjob',
            index=models.Index(fields=['created_at'], name='image_proce_created_e1e96e_idx'),
        ),
        migrations.AddIndex(
            model_name='filesharelink',
            index=models.Index(fields=['share_token'], name='file_share__share_t_1470d0_idx'),
        ),
        migrations.AddIndex(
            model_name='filesharelink',
            index=models.Index(fields=['uploaded_file', 'created_by'], name='file_share__uploade_5fc41f_idx'),
        ),
        migrations.AddIndex(
            model_name='filesharelink',
            index=models.Index(fields=['expires_at'], name='file_share__expires_c212c9_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['uploaded_file', 'access_type'], name='file_access_uploade_388f67_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='file_access_user_id_dac85f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['ip_address', 'accessed_at'], name='file_access_ip_addr_a4cd48_idx'),
        ),
    ]
