# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='stats.achievement', verbose_name='成就'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dishstat',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddIndex(
            model_name='dailystat',
            index=models.Index(fields=['date'], name='daily_stats_date_c5e813_idx'),
        ),
        migrations.AddField(
            model_name='cookingsession',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_sessions', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddField(
            model_name='cookingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='appusagestat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage_stats', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='cookingsession',
            index=models.Index(fields=['user', 'dish'], name='cooking_ses_user_id_8e00b8_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingsession',
            index=models.Index(fields=['start_time'], name='cooking_ses_start_t_9dc879_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagestat',
            index=models.Index(fields=['user', 'session_start'], name='app_usage_s_user_id_8bffe0_idx'),
        ),
    ]
