# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=500, verbose_name='COS文件Key')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('content_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('upload_type', models.CharField(choices=[('dish_image', '菜品图片'), ('user_avatar', '用户头像'), ('other', '其他文件')], default='dish_image', max_length=20, verbose_name='上传类型')),
                ('bucket', models.CharField(max_length=255, verbose_name='存储桶名称')),
                ('region', models.CharField(max_length=50, verbose_name='存储桶地域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'COS文件记录',
                'verbose_name_plural': 'COS文件记录',
                'db_table': 'cos_files',
            },
        ),
    ]
