# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
        ),
        migrations.AddIndex(
            model_name='cosfile',
            index=models.Index(fields=['user', 'upload_type'], name='cos_files_user_id_89513a_idx'),
        ),
        migrations.AddIndex(
            model_name='cosfile',
            index=models.Index(fields=['created_at'], name='cos_files_created_513cb2_idx'),
        ),
    ]
