# Generated by Django 4.2.7 on 2026-06-22 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('tag_type', models.CharField(choices=[('ingredient', '食材'), ('cooking_method', '烹饪方法'), ('cuisine', '菜系'), ('occasion', '场合'), ('diet', '饮食类型'), ('flavor', '口味'), ('difficulty', '难度'), ('time', '时间'), ('custom', '自定义')], max_length=20, verbose_name='标签类型')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('dish_count', models.PositiveIntegerField(default=0, verbose_name='关联菜品数')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name='使用用户数')),
                ('search_keywords', models.JSONField(default=list, verbose_name='搜索关键词')),
                ('synonyms', models.JSONField(default=list, verbose_name='同义词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('tag_count', models.PositiveIntegerField(default=0, verbose_name='标签数量')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签分类',
                'verbose_name_plural': '标签分类',
                'db_table': 'tag_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='推荐权重')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度')),
                ('reason_type', models.CharField(choices=[('co_occurrence', '共同出现'), ('user_preference', '用户偏好'), ('semantic_similarity', '语义相似'), ('category_based', '分类相关'), ('popularity', '流行度'), ('other', '其他')], max_length=20, verbose_name='推荐原因类型')),
                ('reason_data', models.JSONField(default=dict, verbose_name='推荐原因数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签推荐',
                'verbose_name_plural': '标签推荐',
                'db_table': 'tag_recommendations',
                'ordering': ['-weight', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='TagSynonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synonym', models.CharField(max_length=50, verbose_name='同义词')),
                ('language', models.CharField(default='zh', max_length=10, verbose_name='语言')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要同义词')),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签同义词',
                'verbose_name_plural': '标签同义词',
                'db_table': 'tag_synonyms',
                'ordering': ['tag', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='TagUsageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_type', models.CharField(choices=[('dish_creation', '创建菜品'), ('dish_search', '搜索菜品'), ('dish_filter', '筛选菜品'), ('preference_update', '更新偏好'), ('other', '其他')], max_length=20, verbose_name='使用类型')),
                ('context', models.JSONField(default=dict, verbose_name='使用上下文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签使用历史',
                'verbose_name_plural': '标签使用历史',
                'db_table': 'tag_usage_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTagPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='偏好权重')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='用户评分')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户标签偏好',
                'verbose_name_plural': '用户标签偏好',
                'db_table': 'user_tag_preferences',
                'ordering': ['-weight', '-usage_count'],
            },
        ),
    ]
