# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertagpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tagusagehistory',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_usages', to='dishes.dish', verbose_name='关联菜品'),
        ),
        migrations.AddField(
            model_name='tagusagehistory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='tags.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='tagusagehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_usage_history', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tagsynonym',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_synonyms', to='tags.tag', verbose_name='主标签'),
        ),
        migrations.AddField(
            model_name='tagrecommendation',
            name='source_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to='tags.tag', verbose_name='源标签'),
        ),
        migrations.AddField(
            model_name='tagrecommendation',
            name='target_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='tags.tag', verbose_name='目标标签'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='tags.tagcategory', verbose_name='分类'),
        ),
        migrations.AlterUniqueTogether(
            name='usertagpreference',
            unique_together={('user', 'tag')},
        ),
        migrations.AddIndex(
            model_name='tagusagehistory',
            index=models.Index(fields=['user', 'tag'], name='tag_usage_h_user_id_92f684_idx'),
        ),
        migrations.AddIndex(
            model_name='tagusagehistory',
            index=models.Index(fields=['usage_type'], name='tag_usage_h_usage_t_1acb60_idx'),
        ),
        migrations.AddIndex(
            model_name='tagusagehistory',
            index=models.Index(fields=['created_at'], name='tag_usage_h_created_82e79b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagsynonym',
            unique_together={('tag', 'synonym', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='tagrecommendation',
            unique_together={('source_tag', 'target_tag')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_name_38920e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='tags_tag_typ_766b27_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category'], name='tags_categor_1e59f8_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_featured'], name='tags_is_feat_063ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['usage_count'], name='tags_usage_c_26dec2_idx'),
        ),
    ]
