# Generated by Django 4.2.7 on 2026-06-22 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('description', models.TextField(blank=True, verbose_name='菜品描述')),
                ('story', models.TextField(blank=True, verbose_name='菜品故事')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='烹饪时间(分钟)')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难'), ('expert', '专家')], max_length=20, verbose_name='难度')),
                ('cooking_method', models.CharField(choices=[('stir_fry', '炒'), ('steam', '蒸'), ('boil', '煮'), ('fry', '炸'), ('bake', '烤'), ('stew', '炖'), ('roast', '烤'), ('grill', '烧烤'), ('raw', '生食'), ('other', '其他')], max_length=20, verbose_name='烹饪方法')),
                ('cuisine_type', models.CharField(choices=[('chinese', '中式'), ('western', '西式'), ('japanese', '日式'), ('korean', '韩式'), ('thai', '泰式'), ('indian', '印度'), ('vietnamese', '越南'), ('other', '其他')], max_length=20, verbose_name='菜系')),
                ('main_image', models.URLField(blank=True, verbose_name='主图')),
                ('images', models.JSONField(default=list, verbose_name='图片列表')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('ingredients', models.JSONField(default=list, verbose_name='食材列表')),
                ('seasonings', models.JSONField(default=list, verbose_name='调料列表')),
                ('tools', models.JSONField(default=list, verbose_name='厨具列表')),
                ('steps', models.JSONField(default=list, verbose_name='烹饪步骤')),
                ('tips', models.TextField(blank=True, verbose_name='小贴士')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='卡路里')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='蛋白质(g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='碳水化合物(g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='脂肪(g)')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='评分')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='评分次数')),
                ('cooked_count', models.PositiveIntegerField(default=0, verbose_name='烹饪次数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_cooked_at', models.DateTimeField(blank=True, null=True, verbose_name='最后烹饪时间')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('dish_count', models.PositiveIntegerField(default=0, verbose_name='菜品数量')),
                ('total_cooked_count', models.PositiveIntegerField(default=0, verbose_name='总烹饪次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品分类',
                'verbose_name_plural': '菜品分类',
                'db_table': 'dish_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('is_edited', models.BooleanField(default=False, verbose_name='是否编辑过')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='回复数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('reported_count', models.PositiveIntegerField(default=0, verbose_name='举报次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品评论',
                'verbose_name_plural': '菜品评论',
                'db_table': 'dish_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishCookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cooking_date', models.DateField(verbose_name='烹饪日期')),
                ('cooking_time', models.TimeField(verbose_name='烹饪时间')),
                ('actual_cooking_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='实际烹饪时间(分钟)')),
                ('servings', models.PositiveSmallIntegerField(default=1, verbose_name='份量')),
                ('notes', models.TextField(blank=True, verbose_name='烹饪笔记')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='本次评分')),
                ('modifications', models.JSONField(default=dict, verbose_name='修改内容')),
                ('success_level', models.CharField(choices=[('perfect', '完美'), ('good', '良好'), ('ok', '一般'), ('failed', '失败')], default='good', max_length=20, verbose_name='成功程度')),
                ('photos', models.JSONField(default=list, verbose_name='烹饪照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品烹饪历史',
                'verbose_name_plural': '菜品烹饪历史',
                'db_table': 'dish_cooking_history',
                'ordering': ['-cooking_date', '-cooking_time'],
            },
        ),
        migrations.CreateModel(
            name='DishFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='收藏备注')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私有')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品收藏',
                'verbose_name_plural': '菜品收藏',
                'db_table': 'dish_favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评论')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品评分',
                'verbose_name_plural': '菜品评分',
                'db_table': 'dish_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('dish_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜品标签',
                'verbose_name_plural': '菜品标签',
                'db_table': 'dish_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('wechat', '微信'), ('wechat_moments', '朋友圈'), ('qq', 'QQ'), ('weibo', '微博'), ('copy_link', '复制链接'), ('other', '其他')], max_length=20, verbose_name='分享平台')),
                ('share_method', models.CharField(blank=True, max_length=50, verbose_name='分享方式')),
                ('share_content', models.TextField(blank=True, verbose_name='分享内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dishes.dish', verbose_name='菜品')),
            ],
            options={
                'verbose_name': '菜品分享',
                'verbose_name_plural': '菜品分享',
                'db_table': 'dish_shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
