# Generated by Django 4.2.7 on 2026-06-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_shares', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddField(
            model_name='dishrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dishfavorite',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddField(
            model_name='dishfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dishes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dishcookinghistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_history', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddField(
            model_name='dishcookinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_dishes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dishcomment',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dishes.dish', verbose_name='菜品'),
        ),
        migrations.AddField(
            model_name='dishcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dishes.dishcomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='dishcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dishes', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='dishes.dishcategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='dishes.dishtag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='dishshare',
            index=models.Index(fields=['dish', 'user'], name='dish_shares_dish_id_dfe066_idx'),
        ),
        migrations.AddIndex(
            model_name='dishshare',
            index=models.Index(fields=['platform'], name='dish_shares_platfor_373bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishrating',
            unique_together={('dish', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='dishfavorite',
            unique_together={('dish', 'user')},
        ),
        migrations.AddIndex(
            model_name='dishcookinghistory',
            index=models.Index(fields=['dish', 'user'], name='dish_cookin_dish_id_585f38_idx'),
        ),
        migrations.AddIndex(
            model_name='dishcookinghistory',
            index=models.Index(fields=['cooking_date'], name='dish_cookin_cooking_79af83_idx'),
        ),
        migrations.AddIndex(
            model_name='dishcomment',
            index=models.Index(fields=['dish', 'parent'], name='dish_commen_dish_id_120ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='dishcomment',
            index=models.Index(fields=['created_at'], name='dish_commen_created_8d261b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='dishes_name_a4005d_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category'], name='dishes_categor_870a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['author'], name='dishes_author__feabd0_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['rating'], name='dishes_rating_7b0476_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['cooked_count'], name='dishes_cooked__35694c_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['created_at'], name='dishes_created_39b7ca_idx'),
        ),
    ]
